# Generated by Django 5.2.1 on 2025-05-20 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrato', to='cadastros.cliente')),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrato', to='cadastros.sistema')),
            ],
        ),
    ]
