# Generated by Django 5.2.1 on 2025-05-28 00:04
from datetime import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='inicio',
            field=models.DateField(default=datetime.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='termino',
            field=models.DateField(default=datetime.now()),
            preserve_default=False,
        ),
    ]
